# Generated by Django 3.2.13 on 2022-09-11 05:52

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('categories',),
            },
        ),
        migrations.CreateModel(
            name='ShoePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_name', models.CharField(max_length=50)),
                ('trader_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('shoe_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('shoe_size', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1)),
                ('remaining_pairs', models.IntegerField()),
                ('price', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('amount_of_pairs', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shoes.category')),
                ('likes', models.ManyToManyField(blank=True, related_name='shoe_likes', to=settings.AUTH_USER_MODEL)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_pair', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
