# Generated by Django 3.2.13 on 2022-09-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_alter_shoepair_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoepair',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
